#!/bin/bash
# EADB - control android device
# $ eadb [<command>] [<args>...]

# prepare
dp0=$(dirname "$0")
if [[ "${ANDROID_SERIAL}" == "" ]]; then s=""; else s="-s"; fi
${dp0}/extra-adb/devices.sh ${s}

# run command
if [[ "$1" != "" && "$1" != "devices" ]]; then
  c="$1" && shift
  ${dp0}/extra-adb/${c}.sh "$@"
  echo
fi
